-- +goose Up
CREATE TABLE FEEDS (
    ID UUID PRIMARY KEY,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    NAME VARCHAR NOT NULL,
    URL VARCHAR UNIQUE NOT NULL,
    USER_ID UUID NOT NULL REFERENCES USERS (ID) ON DELETE CASCADE,
    CONSTRAINT FK_CUSTOMER FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);

-- +goose Down
DROP TABLE FEEDS;
