-- +goose Up
CREATE TABLE FEED_FOLLOWS (
    ID UUID PRIMARY KEY,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    FEED_ID UUID NOT NULL REFERENCES FEEDS (ID) ON DELETE CASCADE,
    USER_ID UUID NOT NULL REFERENCES USERS (ID) ON DELETE CASCADE,
    CONSTRAINT FK_FEED FOREIGN KEY(FEED_ID) REFERENCES FEEDS(ID),
    CONSTRAINT FK_CUSTOMER FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);

-- +goose Down
DROP TABLE FEED_FOLLOWS;
