-- +goose Up
CREATE TABLE POSTS (
    ID UUID PRIMARY KEY,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    TITLE VARCHAR NOT NULL,
    URL VARCHAR UNIQUE NOT NULL,
    DESCRIPTION VARCHAR,
    PUBLISHED_AT TIMESTAMP,
    FEED_ID UUID NOT NULL REFERENCES FEEDS (ID) ON DELETE CASCADE,
    CONSTRAINT FK_POSTS FOREIGN KEY(FEED_ID) REFERENCES FEEDS (ID)
);

-- +goose Down
DROP TABLE POSTS;
